trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'devendra1203/my-first-project'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
