trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- script: |
    docker build -t devendra1203/my-first-project:latest .
  displayName: Build Docker Image